### PR TITLE
Mobile menu view

### PR DESCRIPTION
**Pull request by teddy4445**
Adding the mobile header menu view with close and open logic.
Next step: implementing the "burger" and fixes to the desktop menu to be one line by @nspitzern

### CODE REVIEW

**Comment by arielfenster** [comment]
looks good

**Review by arielfenster — APPROVED** [review]

**Review by nspitzern — APPROVED** [review]
Looks good

**Comment by nspitzern** [comment]
in main page: remove end script tag - causes an error

**Comment by teddy4445** [comment]
Merge @nspitzern fixes for the mobile style and by that finishing the header menu for desktop, tablat and mobile

**Pull request merged**
